### ISSUE TITLE
generate indicators : error on installing requirements

### ISSUE THREAD

**Issue by answerquest** [CanalTP/accra_dashboard#15]
Getting an error at the second command given on Readme, can't understand exactly what's going wrong here : 

> Create the virtual environnemnt with the required packages : `pipenv --python 3.6 install -r indicators_generation/requirements.txt`

```
$ pipenv --python 3.6 install -r indicators_generation/requirements.txt
Creating a virtualenv for this project…
Pipfile: /mnt/STUFF/accra_dashboard/Pipfile
Using /usr/bin/python3.6 (3.6.7) to create virtualenv…
⠼ Creating virtual environment...Using base prefix '/usr'
New python executable in /home/nikhil/.local/share/virtualenvs/accra_dashboard-7yEYVClM/bin/python3.6
Also creating executable in /home/nikhil/.local/share/virtualenvs/accra_dashboard-7yEYVClM/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python3.6

✔ Successfully created virtual environment! 
Virtualenv location: /home/nikhil/.local/share/virtualenvs/accra_dashboard-7yEYVClM
Requirements file provided! Importing into Pipfile…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
⠧ Locking...
Traceback (most recent call last):
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 109, in expect_loop
    return self.timeout()
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f92846245f8>
searcher: searcher_re:
    0: re.compile('\n')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikhil/.local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/cli/command.py", line 254, in install
    editable_packages=state.installstate.editables,
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/core.py", line 1874, in do_install
    keep_outdated=keep_outdated
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/core.py", line 1244, in do_init
    pypi_mirror=pypi_mirror,
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/core.py", line 1068, in do_lock
    lockfile=lockfile
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/utils.py", line 649, in venv_resolve_deps
    c = resolve(cmd, sp)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/utils.py", line 517, in resolve
    result = c.expect(u"\n", timeout=environments.PIPENV_INSTALL_TIMEOUT)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/delegator.py", line 215, in expect
    self.subprocess.expect(pattern=pattern, timeout=timeout)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/home/nikhil/.local/lib/python3.6/site-packages/pipenv/vendor/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: <pexpect.popen_spawn.PopenSpawn object at 0x7f92846245f8>
searcher: searcher_re:
    0: re.compile('\n')
<pexpect.popen_spawn.PopenSpawn object at 0x7f92846245f8>
searcher: searcher_re:
    0: re.compile('\n')
```

**Comment by prhod** [comment]
Hello, I've asked some help from fellow developers to help you with this. It may take few days. Can you tell me details about your environment ? Ubuntu ? 
Best regards

**Comment by prhod** [comment]
Hello, I'm not able to reproduce your problem, I'm using python 3.6.6 and I'm also on Ubuntu 18.04 64-bit.
Can you try to delete the Pipfile (and Pipfile.lock if created beforehand) and try: 
* creating a blank virtual env : `pipenv --python 3.6 install`
* activate the virtual env : `pipenv shell`
* install the packages referenced in the indicators_generation/requirements.txt one by one, for exemple `pip install pandas` ?
It may help to understand what the problem is ...

**Comment by answerquest** [comment]
:+1:  Yes it worked that way.
On running, there was one FutureWarning:
```
$ python indicators_generation/indicators_generation.py
indicators_generation/indicators_generation.py:67: FutureWarning: Series.data is deprecated and will be removed in a future version
  for coord in zip(shape_points["shape_pt_lon"].data, shape_points["shape_pt_lat"].data):
```
But it ran successfully. The `data/accra_indicators.db` file got populated to 4.9MiB.

I'm now running the docker command, it's still downloading (their servers have been getting slow in my parts these days). There was one warning flashed about mapbox api key:
```
$ docker-compose up -d
WARNING: The MAPBOX_API_KEY variable is not set. Defaulting to a blank string.
Creating network "accradashboard_default" with the default driver
Creating volume "accradashboard_redis" with default driver
Pulling redis (redis:latest)...
```
I do have a basic key.. if needed I can put it in, but I'll need to know how.

**Comment by answerquest** [comment]
If you're using virtualenv anyways, you might want to put strict version numbers on the requirements.

**Comment by answerquest** [comment]
Up and running! :+1:  Great work, guys! I'll work on figuring out how to plug in other GTFS feeds and get back to you if I make any headway. 

I suggest you post about this fabulous work on https://groups.google.com/forum/#!forum/transit-developers and https://github.com/CUTR-at-USF/awesome-transit . (Both maintained by the same folks.. one is a discussion forum and the other is a one-stop listing of GTFS resources)

And just a suggestion: Detail out in a wiki page or so if there is any part of your dashboard that depends on data external to your GTFS feed, and if there are any assumed multipliers etc you have applied (like for the CO2 emissions).

Also, I will share what motivated me to search online for "gtfs superset" that led me to your project: I want to try adding a dashboard like yours to my static-gtfs-manager project : https://github.com/WRI-Cities/static-GTFS-manager . But that one runs on much simpler tech; you could just as well absorb a gtfs manager/editor into your project! Let me know if there's chances for collaboration - it'll happen much quicker if the devs talk with each other.

Please feel free to close this ticket if you feel its done.

**Comment by prhod** [comment]
Thanks for the feedbacks and glad you managed to make it run ^^
You're right about the virtual_env and the packages version. Maybe you can help us with a PR ?
For the MAPBOX_API_KEY, if I remember correctly, it's an optional feature of superset when you want to display a custom map, but it wasn't used in this project.

**Comment by prhod** [comment]
@answerquest I've kept this issue open to take time about your remarks, but this project is not aimed to be maintained. I'll let it that way for the moment, but I'm glad someone found it useful in anyway ! 
FYI some people here are using your GTFS editor, thanks a lot :+1:
